services:
  nexus:
    container_name: nexus
    platform: linux/amd64
    image: sonatype/nexus3:latest
    ports:
      - ${NEXUS_PORT:-8081}:8081
      - ${NEXUS_HEALTH_PORT:-8085}:8085
    volumes:
      - ./nexus-data:/nexus-data
    user: "200:200"
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-1}
          memory: ${MEM_LIMIT:-1G}
    restart: always
