services:
  mongodb:
    image: mongo:8.0.3-noble
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: always
    networks:
      - mongo_net

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb_data:
  mongodb_config:

networks:
  mongo_net:
    driver: bridge