version: "1.0"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    platform: linux/amd64
    container_name: MS_SQL_Server
    restart: always
    environment:
      SA_PASSWORD: "root@ABC123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - 1433:1433
    networks:
      - dev

volumes:
  mssql-data:
    driver: local

networks:
  dev:
    driver: bridge

# Address in DatGrip jdbc:sqlserver://localhost\databasename:1433
# "Data Source=localhost,1433;Initial Catalog=db;User id=sa;Password=Pass123!;MultipleActiveResultSets=True"
