services:
  redis:
    image: redis:latest
    container_name: redis-service
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db